
== Terms and definitions

=== Metaverse core concepts

==== metaverse

{{interactive}} {{virtual world}} that incorporates {{spatial referencing}}
experienced through {{immersive}} technologies


==== artificial intelligence
preferred:[AI]

capacity of computers or other machines to exhibit or simulate intelligent
behavior

[.source]
<<IEEE_7010_2020>>


==== assistive technology

piece of equipment, product system, hardware, software or service that is used
to enable, maintain or improve functional capabilities of individuals with
disabilities

[.source]
<<ITU-T_F_791>>

==== cloud computing

paradigm for enabling network access to a scalable and elastic pool of shareable
physical or virtual resources with self-service provisioning and administration
on-demand

[.source]
<<ISO_IEC_17788_2014,clause=3.2.5>>


==== decentralized identifier

[%metadata]
abbreviation-type:: initialism

preferred:[DID]

identifier in the format of the W3C Decentralized Identifier

[.source]
<<w3c_did>>



==== digital human

realistic virtual human representations created using advanced simulation
technology


==== digital twin

digital representation of an object of interest

NOTE: A digital twin may require different capabilities (e.g., synchronization,
real-time support) according to the specific domain of application.

[.source]
<<ITU-T-Y_4600>>


==== distributed computing

model of computing in which a set of nodes coordinates its activities by means
of digital messages passed between the nodes

[.source]
<<ISO_IEC_23188_2020,clause=3.1.1>>


==== distributed ledger

a {{ledger}} that is shared across a set of DLT nodes and synchronized between
the DLT nodes using a consensus mechanism

[.source]
<<ISO_22739_2024,clause=3.22>>

==== digital asset

asset that exists only in digital form or which is the digital representation of
another asset

[.source]
<<ISO_24165-1_2021,clause=3.9>>

==== digital identity

information used by information systems to represent an external agent, a
person, organization, application, or device


==== edge computing

{{distributed computing}} in which processing and storage takes place at or near the
edge, where the nearness is defined by the system's requirements

[.source]
<<ISO_IEC_23188_2020,clause=3.1.3>>

==== edge device

device that provides an entry point into enterprise or service provider core
networks

[example]
Gateways, routers, switches, multiplexers, and a variety of other access devices.

[.source]
<<w3c_wot>>

==== immersive

creating the illusion of being inside a computer-generated scene

[.source]
<<ISO-IEC_19775-1>>


==== interactive

pertaining to a system or mode of operation in which each user entry causes a response from or action by the system

[.source]
<<ISO-IEC-IEEE_24765_2017,clause=3.2050>>, removed second definition.


==== Internet of Things

system of entities (including cyber-physical devices, information resources, and
people) that exchange information and interact with the physical world by
sensing, processing information, and actuating

[.source]
<<IEEE_2413_2019>>, dropped article.


==== interoperability

ability of two or more systems or applications to exchange information and to
mutually use the information that has been exchanged

[.source]
<<ISO_IEC_17788_2014,clause=3.1.5>>


==== ledger

information store that keeps records of transactions that are intended to be
final, definitive and immutable

[.source]
<<ISO_22739_2024,clause=3.43>>


==== information security

preservation of confidentiality, integrity and availability of information

NOTE: In addition, other properties, such as authenticity, accountability,
non-repudiation, and reliability can also be involved.

[.source]
<<ISO-IEC_27000_2018,clause=3.28>>


==== spatial referencing

method to describe a position within a context

NOTE: A position may the form of a label, code or coordinate tuple.

NOTE: Definition modified from <<ISO_19111_2019,clause=3.1.56>> "spatial reference".


==== virtual world
alt:[cyber world]

simulated environment that can be accessed by multiple users through an online
interface

NOTE: The simulated environments are often interactive.

NOTE: The physical world in which people live, and the related characteristics,
will be referred to as the "real world" to differentiate it from a virtual
world.

[.source]
<<ISO-IEC_27032-2012,clause=4.51>>


==== virtual office

3-D virtual scene replicating office space of an organization, providing users
with an {{immersive}} experience


==== user-generated content
alt:[UGC]

content created by users within the {{metaverse}}

NOTE: UGC is often facilitated by simplified editing tools.



=== Metaverse technology domains

==== industrial metaverse

{{metaverse}} that integrates virtual and physical realities to create a
sophisticated digital industrial ecosystem, enhancing real-world processes
through virtual simulations and strengthening the entire industrial and value
chain with increased intelligence, collaboration, openness, service orientation,
and interconnectivity

==== financial metaverse

{{metaverse}} enabling a new type of financial business where the physical world
and the mirrored digital world are symbiotic

==== education metaverse

{{metaverse}} enabling a multi-sensory {{immersive}} classroom connecting virtual
and reality, enabling knowledge acquisition, participation, and creation

==== healthcare metaverse

{{metaverse}} that enables the digital, intelligent and accurate medical
information platform that breaks space-time restrictions and technical barriers
of the original medical system

==== eCommerce metaverse

{{metaverse}} that enables marketing towards users, creating personalized, emotional
and social marketing scenes through metaverse technology and content

==== game metaverse

{{metaverse}} that enables the evolution of gaming that embodies four
characteristics: immersion, accessibility, accessibility and extensibility

==== social metaverse

{{metaverse}} that creates a holographic virtual reality that integrates the
advantages of online and offline social networking, using {{AR}}, {{VR}}, {{XR}}
and other technologies




=== XR concepts

==== extended reality
preferred:[XR]

environments experienced through human-machine sensory interactions
commonly composed of real world and virtual elements

NOTE: Extended reality covers {{virtual reality}}, {{augmented reality}} and
{{mixed reality}} environments.


==== augmented reality
preferred:[AR]

interactive experience of a real-world environment whereby the objects that
reside in the real world are augmented by computer-generated perceptual
information

// 20230113 original def
// Human perception is enhanced with additional computer-generated sensorial input
// to create a new user experience, including, but not restricted to, enhancing
// human vision by combining natural with digital offers.
// <<IEEE_1589_2020>>
//1589-2020 - IEEE Standard for Augmented Reality Learning Experience Model

[.source]
<<ISO_IEC_18038_2020,clause=3.1>>

==== mixed reality
preferred:[MR]

display continuum in which both real and virtual images are combined in some way
and in some proportion

NOTE: Augmented reality and virtual reality are considered to be on the mixed
reality continuum.

[.source]
<<ISO-IEC_TR_23843_2020,clause=3.4>>, added Note 1 to entry.


==== virtual reality
preferred:[VR]

artificial environment presented in the computer

[.source]
<<ISO_IEC_TR_18121_2015,clause=3.6>>, dropped article


==== mixed reality system

system that uses a mixture of representations of physical world data and
{{virtual world}} data as its presentation medium

[.source]
<<ISO_IEC_18039_2019,clause=3.1.13>>


==== mixed and augmented reality
preferred:[MAR]

integration of real and virtual worlds including {{mixed reality}} and
{{augmented reality}}

NOTE: MAR is often used interchangeably with MR.

[.source]
<<ISO_IEC_18038_2020>>


=== Metaverse interfaces

==== cyber physical system
preferred:[CPS]

system with digital, analogue, cyber, physical and human components interacting
with each other, engineered to function through integrated physics and logic

[.source]
<<IWA_39_2022,clause=3.1>>


=== human-computer interface
preferred:[HCI]

boundary across which physical interaction between a human being and a computing
device takes place

NOTE: Definition originates from <<ISO-IEC_TR_10000-3_1998,clause=3.2.5>>.


=== brain-computer interface
preferred:[BCI]

device that quantifies central nervous system activity and translates them into
digital outputs

NOTE: A brain-computer interface may facilitate bi-directional communication
between the brain and a computing device.

NOTE: A brain-computer interface is a type of human-computer interface that
enables direct communication between the brain and an external device.


==== haptics

input or output device that senses or actuates the body's movements by means of physical contact with the user

[.source]
<<ISO-IEC_23093-1_2022,clause=3.1.5>>


==== game console

dedicated electronic device designed to play video games

==== internet of things
alt:[IoT]

infrastructure of interconnected entities, people, systems and information resources, together with services which process and react to information from the physical world and the virtual world

[.source]
<<ISO-IEC_20924_2021,clause=3.2.4>>

==== wearable device

{{IoT}} device designed for operation near to, on, or inside of a body

NOTE: Wearable devices often have a variety of sensing abilities, but limited power capacity constraining communication and data processing abilities. As critical devices of the IoT, it is considered that the communication between wearable devices and a network might not require any human intervention. Wearable devices include electronic devices usable by humans, animals, and other organisms.

[.source]
<<ISO-IEC_20924_2024,clause=3.1.35>>


=== Metaverse spatial

==== simultaneous localization and mapping
preferred:[SLAM]

technique used in robotics and computer vision to create a map of an unknown
environment while simultaneously keeping track of an agent's location within it

==== neural radiance fields
preferred:[NeRF]

method for synthesizing novel views of complex scenes by optimizing a continuous
3D scene representation

==== photogrammetry

technique of measurement using photographs, for example aerial photographs, to determine, primarily, geometric properties such as size, location and form of objects

NOTE: Photogrammetric measurement is often used for mapping, but also has some engineering applications.

[.source]
<<ISO_7078_2020,clause=3.1.5>>

==== computer vision
alt:[artificial vision]

capability of a functional unit to acquire, process, and interpret visual data

NOTE: Computer vision involves the use of visual sensors to create an electronic or digital image of a visual scene.

[.source]
<<ISO-IEC_2382_2015,clause=2123787>>, Note to entries 2-4 omitted.


==== computer graphics

methods for converting data to or from graphic displays by a computer

[.source]
<<ISO_6707-2_2017,clause=3.2.17>>


==== point cloud

discrete set of data points in space

NOTE: A point cloud typically representing a 3D shape or object.




=== Extended metaverse concepts

==== C-Meta

low-carbon social metaverse under the Web 3.0 architecture, aiming to build a
new green and energy-saving digital economy


=== Governance


==== stakeholder
// from https://github.com/Spatial-Web-Foundation/SWF-Corpus_and_IEEEP2874-D2/issues/397

role, position, individual, organization, or classes thereof, having an
interest, right, share, or claim, in an entity of interest

[example]
End users, operators, acquirers, owners, suppliers, architects, developers, builders, maintainers, regulators, taxpayers, certifying agencies, and markets.

[.source]
<<ISO_IEC_IEEE_42010_2022,clause=3.17>>, dropped article

==== stakeholder perspective
// from https://github.com/Spatial-Web-Foundation/SWF-Corpus_and_IEEEP2874-D2/issues/397

way of thinking about an entity of interest, especially as it relates to
concerns

[.source]
<<ISO_IEC_IEEE_42010_2022,clause=3.18>>, The original example has been removed.
